### ISSUE TITLE
Javascript part not working

### ISSUE THREAD

**Issue by matkuki** [emekoi/joker#1]
Hi @emekoi ,

I compiled the `src/joker.nim` to an executable and `src/jokerpkg/views/main.nim` to javascript and adjusted the path of the `main.js` file to the `src/jokerpkg/views/nimcache/main.js` path in `joker.nim`, but the javascript part of the page does not seem to be working. I even replaced the `main.js` file contents to just `alert("HELLO");` and it still doesn't execute.
I do not have much experience with web development, so I do not now what to try next. Any ideas?

My system:
- Windows 10 x64
- Nim 0.18.1 Devel version (mingw-w64 gcc compiler)

Thanks

**Comment by matkuki** [comment]
I forgot to do the `build_js` step and copied the `public` directory to where the executable is, so now it's working.
How does the application know that it should look into the `public` directory for `views/main.nim.js`?

Thanks

**Comment by emekoi** [comment]
by default jester looks for a directory named `public` and serves files from there.

**Comment by matkuki** [comment]
@emekoi Thanks!
